"use strict";
exports.__esModule = true;
var Auto_1 = require("./Auto");
var ParcoMacchine_1 = require("./ParcoMacchine");
var Cliente_1 = require("./Cliente");
var Cliente_2 = require("./Cliente");
var PM1 = new ParcoMacchine_1.ParcoMacchine();
var A1 = new Auto_1.Auto("AAA", "1", "blu");
var A2 = new Auto_1.Auto("BBB", "2", "nera");
var A3 = new Auto_1.Auto("CCC", "3", "fucsia");
var C1 = new Cliente_1.Cliente(1, "Mario", "Rossi");
var C2 = new Cliente_2.ClienteBusiness(2, "Luca", "Bianchi", 1000);
PM1.addAuto(A1);
PM1.addAuto(A2);
PM1.addAuto(A3);
// PM1.mostraAuto();
// console.log(C2.getSconto());
C1.verificaBusiness();
